version: '3'
services: 
   docker-mysql:
      image: mysql:latest
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=tmsdb
         - MYSQL_PASSWORD=root
   eurekaserver:
      image: 'fse2/tripmanagement_eureka_service'
      depends_on:
         - docker-mysql
      ports:
         - "8761:8761"
   configserver:
      image: 'fse2/tripmanagement_config_service'
      depends_on:
         - docker-mysql
         - eurekaserver
      ports:
         - "8888:8888"
      environment:
         - GITREPO=https://github.com/deb82banerjee/FSE_S2_TripManagement_Config.git
         - EUREKA_SERVER=http://eurekaserver:8761/eureka
   zuulserver:
      image: 'fse2/tripmanagement_zuul_service'
      restart: always
      ports:
         - "8081:8081"
      depends_on:
         - docker-mysql
         - eurekaserver
         - configserver
      command: ["./wait-for-it.sh", "configserver:8888","java","-jar", "tripmanagement_zuul_service-0.0.1-SNAPSHOT.jar"]
      #,"--","./wait-for-it.sh", "eurekaserver:8761", "--", "java","-jar", "tripmanagement_zuul_service-0.0.1-SNAPSHOT.jar"]
#      environment:
#         - EUREKA_SERVER=http://eurekaserver:8761/eureka