version: '3'
services: 
   docker-mysql:
      image: mysql:latest
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=tmsdb
         - MYSQL_PASSWORD=root
   tripmanagement-ui:
      image: 'tripmanagement-ui'
      restart: always
      ports:
         - "4200:80"
   eurekaserver:
      image: 'fse2/tripmanagement_eureka_service'
      depends_on:
         - docker-mysql
      ports:
         - "8761:8761"
   configserver:
      image: 'fse2/tripmanagement_config_service'
      depends_on:
         - docker-mysql
         - eurekaserver
      ports:
         - "8888:8888"
      environment:
         - GITREPO=https://github.com/deb82banerjee/FSE_S2_TripManagement_Config.git
         - EUREKA_SERVER=http://eurekaserver:8761/eureka
   zuulserver:
      image: 'fse2/tripmanagement_zuul_service'
      restart: always
      ports:
         - "8081:8081"
      depends_on:
         - docker-mysql
         - eurekaserver
         - configserver
      environment:
         - CONFIG_SERVER=http://configserver:8888
         - EUREKA_SERVER=http://eurekaserver:8761/eureka
   authserver:
      image: 'fse2/tripmanagement_auth_service'
      restart: always
      depends_on:
         - docker-mysql
         - eurekaserver
         - configserver
      ports:
         - "1111:1111"
      environment:
         - EUREKA_SERVER=http://eurekaserver:8761/eureka
         - DATASOURCEURL=jdbc:mysql://docker-mysql:3306/tmsdb?createDatabaseIfNotExist=true
         - DBUSER=root
         - DBPASSWORD=root
   driverserver:
      image: 'fse2/tripmanagement_driver_service'
      restart: always
      depends_on:
         - docker-mysql
         - eurekaserver
         - configserver
      ports:
         - "3333:3333"
      environment:
         - EUREKA_SERVER=http://eurekaserver:8761/eureka
         - DATASOURCEURL=jdbc:mysql://docker-mysql:3306/tmsdb?createDatabaseIfNotExist=true
         - DBUSER=root
         - DBPASSWORD=root
   riderserver:
      image: 'fse2/tripmanagement_rider_service'
      restart: always
      depends_on:
         - docker-mysql
         - eurekaserver
         - configserver
      ports:
         - "4444:4444"
      environment:
         - EUREKA_SERVER=http://eurekaserver:8761/eureka
         - DATASOURCEURL=jdbc:mysql://docker-mysql:3306/tmsdb?createDatabaseIfNotExist=true
         - DBUSER=root
         - DBPASSWORD=root
   adminserver:
      image: 'fse2/tripmanagement_admin_service'
      restart: always
      depends_on:
         - docker-mysql
         - eurekaserver
         - configserver
      ports:
         - "2222:2222"
      environment:
         - EUREKA_SERVER=http://eurekaserver:8761/eureka
         - DATASOURCEURL=jdbc:mysql://docker-mysql:3306/tmsdb?createDatabaseIfNotExist=true
         - DBUSER=root
         - DBPASSWORD=root
         